const CALCULATOR_CLEAR = 'CALCULATOR_CLEAR';
const CALCULATOR_OPERATION_UPDATE = 'CALCULATOR_OPERATION_UPDATE';
const CALCULATOR_APPLY_RESULT = 'CALCULATOR_APPLY_RESULT';

export {
  CALCULATOR_CLEAR,
  CALCULATOR_OPERATION_UPDATE,
  CALCULATOR_APPLY_RESULT,
};