
const CALCULATOR_CLEAR = 'CALCULATOR_CLEAR';
const CALCULATOR_OPERATION_UPDATE = 'CALCULATOR_OPERATION_UPDATE';
const CALCULATOR_CALCULATE_RESULT = 'CALCULATOR_CALCULATE_RESULT';

export {
  CALCULATOR_CLEAR,
  CALCULATOR_OPERATION_UPDATE,
  CALCULATOR_CALCULATE_RESULT,
};